### ISSUE TITLE
Feature request: explicit method to get posed mesh joints

### ISSUE THREAD

**Issue by neoglez** [ahmedosman/STAR#10]

**Comment by ahmedosman** [comment]
Hi @neoglez , first thanks for the wonderful pull request. 

In your pull request, the Joint regressor was used to regress the joints from the posed mesh. This is not the correct way to compute the posed joints. The joint regressor only use, is for computing the joint location in T-Pose. To get the posed joints you simply apply the kinematic chain of the transformation to the regressed joints in T-Pose, I added the model posed joints for the torch module line 144-152 https://github.com/ahmedosman/STAR/blob/master/star/pytorch/star.py 

In all frameworks, you can get the 24 posed joints star.J_transformed 

Thanks again for the PR. 
Ahmed
