### ISSUE TITLE
Changing Betas does not change shape of models

### ISSUE THREAD

**Issue by michael-p-sachen** [ahmedosman/STAR#13]
Hi,
When I edit the beta's of a model it does not result in a change to the shape of the generated Model
Is this the correct way to change the body shape?

I am using the chumpy version of STAR

**Comment by ahmedosman** [comment]
Hi @michael-p-sachen , I am glad someone is using the chumpy code still. 
Could you pull again from remote, and check this example here:

https://github.com/ahmedosman/STAR/blob/master/demo/load_chumpy.py

Line 27-32 varies the 'betas' +/- 3 standard deviation. 

Can I close this issue now?

**Comment by michael-p-sachen** [comment]
Thanks Working Great!
Thank you for your project
