### ISSUE TITLE
The error with output mesh ?

### ISSUE THREAD

**Issue by sarahxinxi** [ahmedosman/STAR#16]
In compare_frameworks.py, I want to see the result of mesh. I write obj result with tf_star,d and model.r respectively, all these results are wrong, but obj result with v_shaped is right.  What's wrong

**Comment by ahmedosman** [comment]
Hi @sarahxinxi , What do you mean by wrong? 

This demo is a unit test. It samples pose and shape parameters randomly from a gaussian distribution and compare the output from all frameworks. The output mesh will not look sensible, because the input is not sensible. 

Can I close this issue now?

**Comment by sarahxinxi** [comment]
> Hi @sarahxinxi , What do you mean by wrong?
> 
> This demo is a unit test. It samples pose and shape parameters randomly from a gaussian distribution and compare the output from all frameworks. The output mesh will not look sensible, because the input is not sensible.
> 
> Can I close this issue now?

So how can I get a sensible output mesh with a pose not in a  T-pose

**Comment by ahmedosman** [comment]
Hi @sarahxinxi , you can  fit STAR to SMPL meshes from the amass dataset  https://amass.is.tue.mpg.de/
