### ISSUE TITLE
how to get pose by given joints 3D-locations (24,3)?

### ISSUE THREAD

**Issue by wenhaochai** [ahmedosman/STAR#23]
Thanks for your great work with excellent performance!
I am now trying ton use your trained model(like female.npz) and the actually the given 3d-location (24,3) to rebuild a mesh.
But I notice that the model only get a pose input. I am already know that the pose can be compute by the two vector(before and after). My question is, **what exact the rest-pose be**, I mean to compute every pose, it seems like we must know the situation when pose is 0 (T-pose).
I would be most grateful if you could answer my questions in your busy schedule!

**Comment by wenhaochai** [comment]
is ik(inserve kinematic) works?

**Comment by ahmedosman** [comment]
We do not provide inverse kinematics code for STAR at the moment.
