### ISSUE TITLE
STAR pose prior needed

### ISSUE THREAD

**Issue by nikjetchev** [ahmedosman/STAR#24]
Hi
first thanks for sharing that code, it is a very cool project. 

I have a use case when I am optimizing the pose and shape parameters w.r.t. some animation loss function, but the model makes very unnatural appearance. Do you have a function or data which gives a statistical prior on the reasonable pose/shape parameters?

(e.g. as SMPL has, e.g. https://github.com/vchoutas/smplify-x/blob/master/smplifyx/prior.py )

Or at the very least, what is the numerical interval of the pose and shape parameters? 
Are the shape parameters actually angles in radians?

Or would it be a good idea to convert the old SMPL data into STAR format and calculate the prior myself?

thanks, any help will be appreciated

**Comment by ahmedosman** [comment]
Hi @nikjetchev, the STAR kinematic tree is based on the SMPL kinematic tree. So you can re-use pose prior for SMPL (V-poser, GMM pose prior) also for STAR.
