### ISSUE TITLE
Is there the sample we can run directly?

### ISSUE THREAD

**Issue by shuxuzhipeng** [ahmedosman/STAR#3]

**Comment by ahmedosman** [comment]
Did you check the samples under demo/?

**Comment by shuxuzhipeng** [comment]
I mean how to apply it, just like SMPL samples, with the result of inference of image.

**Comment by neoglez** [comment]
@shuxuzhipeng please see my pull request, specially https://github.com/neoglez/STAR/blob/master/demo/load_chumpy.py

**Comment by ahmedosman** [comment]
Hi @shuxuzhipeng , we don't provide image regressors or fitting to images sample code.
